name: test1322
favicon: null
layout_spectrum: 0.06742733041755855
typography_spectrum: 0.7186489854939282
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.15523580135777593
  lightness: 0.9524437633808702
  saturation: 0.5062402116600424
  rhythmicContrast: 0.5093445761594921
purpose: []
